# Generated by Django 4.2.3 on 2023-07-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perk",
            name="detail",
        ),
        migrations.AddField(
            model_name="perk",
            name="details",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="perk",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
