# Generated by Django 4.2.3 on 2023-07-31 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_alter_room_amenities_alter_room_category"),
        ("experiences", "0004_alter_experience_category_alter_experience_perks"),
        ("medias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="experience",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="experiences.experience"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="room",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="rooms.room"),
        ),
    ]
