# Generated by Django 4.2.3 on 2023-07-31 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_alter_room_amenities_alter_room_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("experiences", "0004_alter_experience_category_alter_experience_perks"),
        ("wishlists", "0003_alter_wishlist_experiences_alter_wishlist_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="experiences",
            field=models.ManyToManyField(blank=True, related_name="wishlists", to="experiences.experience"),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="owner",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wishlists", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="rooms",
            field=models.ManyToManyField(blank=True, related_name="wishlists", to="rooms.room"),
        ),
    ]
