name: Pull Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pip install ruff

    - name: Get files changed
      id: file_changed
      uses: trilom/file-changes-action@v1.2.4
      with:
        prNumber: ${{ github.event.number }}
        output: " "

    - name: Pre-commit
      uses: pre-commit/action@v2.0.3
      with:
        extra_args: --files ${{ steps.file_changed.outputs.files }}
